version: '3.1'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: docassist
      POSTGRES_PASSWORD: aakashchaitanya
      POSTGRES_DB: medicine
    volumes:
      - ./database/postgresdb/data:/var/lib/postgresql/data
      - ./database/queries:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@docassist.example.com
      PGADMIN_DEFAULT_PASSWORD: aakashchaitanya
    ports:
      - "5400:80"
    depends_on:
      - db